### PR TITLE
Add code to base gulpfile.js to autoload dev plugins

### PR DESCRIPTION
**Pull request by RoryH**

### CODE REVIEW

**Comment by ahollinshead** [comment]
Don't see any problem, just not sure what the difference is going to be - did they fail to load before?

**Comment by RoryH** [comment]
So before we basically had to have something in here to load the swig plugins manually.. this will make that process automatic.

example of previous gulpfile.js we had in web-checkout:

```
'use strict';
/*
 ________  ___       __   ___  ________
|\   ____\|\  \     |\  \|\  \|\   ____\
\ \  \___|\ \  \    \ \  \ \  \ \  \___|
 \ \_____  \ \  \  __\ \  \ \  \ \  \  ___
  \|____|\  \ \  \|\__\_\  \ \  \ \  \|\  \
    ____\_\  \ \____________\ \__\ \_______\
   |\_________\|____________|\|__|\|_______|
   \|_________|

   It's delicious.
   Brought to you by the fine folks at Gilt (http://github.com/gilt)

*/
var gulp = require('gulp'),
  swig = require('@gilt-tech/swig')(gulp);

// only require dev dependencies when in development mode,
// or when the environment hasn't been defined.
if (!process.env.NODE_ENV || process.env.NODE_ENV === 'development') {
  require('@gilt-tech/swig-run')(gulp, swig);
}
```

**Comment by ahollinshead** [comment]
so now you just add a dependency to @gilt-tech/swig-run instead in your package.json devDependencies?

**Comment by RoryH** [comment]
Yeah, and/or the new nova deploy tool module @gilt-tech/swig-nova.. will obviously also support future modules of the same type

**Comment by RoryH** [comment]
@njprrogers happy?

**Comment by njprrogers** [comment]
💣 💥 💥 💥

**Pull request merged**
